name: release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
        
      - name: Setup
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: CLANG64
          install: >-
            base-devel
            git
            zip
            mingw-w64-clang-x86_64-toolchain
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-SDL2
            mingw-w64-clang-x86_64-openblas
            mingw-w64-clang-x86_64-gcc
            mingw-w64-clang-x86_64-vulkan-devel
            mingw-w64-clang-x86_64-shaderc
            
      - name: Build using CMake
        shell: msys2 {0}
        run: |
            cmake -B build -DWHISPER_SDL2=ON -DBUILD_SHARED_LIBS=ON -DGGML_VULKAN=ON -DGGML_OPENBLAS=ON
            cmake --build build --config Release -j
            zip -j release.zip build/bin/*
            
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: Release ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          name: build-${{ github.run_id }}
          files: |
            release.zip
